### ISSUE TITLE
Images are not shown at "actual size" for reviews

### ISSUE THREAD

**Issue by wilka** [int2017/Inspicio#3]
One issue with this page layout (and the previous page layout) is that it's important for the images to be displayed at actual size. The images are mostly going to be screen shots, and they need to be displayed inside in Inspicio at the same as they really are on screen, so we can review the layout, spacing, etc. properly.

At the moment, that's not what happens. For example...

The screenshot (click for bigger):
![image](https://user-images.githubusercontent.com/1788792/27921346-619b369e-626f-11e7-87aa-225a483e0090.png)

Displayed in Inspicio (click for bigger):
![image](https://user-images.githubusercontent.com/1788792/27921417-a9949cf6-626f-11e7-9f1d-1b3f9804cff8.png)

**Comment by wilka** [comment]
@gecevicius seeing as you've picked this one up, I've assigned it to the Sprint 2 milestone

**Comment by gecevicius** [comment]
Fixed.

**Comment by wilka** [comment]
Hmmm, it's still showing up squashed for me. I've made sure my cache etc. is cleared, so I shouldn't have any of the old stuff lying around.

![image](https://user-images.githubusercontent.com/1788792/27965178-c5ce0baa-6332-11e7-91f4-a6f619fe4abd.png)

If I stretch my browsers over both screens to make it really big, then I do get a full size image - but the default seems to still be squashed.

**Comment by gecevicius** [comment]
It still stays the same aspect ratio by default and in the lightbox.  If the image is bigger than the window the  user will have to scroll sideways. Unless I'm misunderstanding something?

**Comment by wilka** [comment]
Scrolling is fine (horizontal or vertical) - even if it can be a bit awkward. For UI reviews, it's more important than the images are actual size. Otherwise you're not reviewing what the user would see when you're adding location comments. I could open the image in a new window, then add comments in window A while looking at alignment etc. in window B, but that would be pretty awkward. 

I suspect it'll be pretty common for the screenshots to be almost 100% size, because they're not going to be a full desktop screen most of the time - just an area (e.g. a popup dialog), so people will be reviewing the slightly-off screen without realising it.

**Comment by gecevicius** [comment]
Should be okay now.
